# Generated by Django 3.2.10 on 2022-01-10 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import merryphonebook.phonebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(blank=True, max_length=255)),
                ('phoneNum', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook_category', to='phonebook.category')),
            ],
            bases=(models.Model, merryphonebook.phonebook.models.NumberModel),
        ),
    ]
